const $=id=>document.getElementById(id);
let language='ru';try{const saved=localStorage.getItem('null-escape-language');if(UI[saved])language=saved}catch{}
let chapters=LOCALES[language],u=UI[language];
let level=0,solved=Array(5).fill(false),collected=Array(5).fill(false),player={x:3,y:8},steps=0,finished=false,ending=null,infoKind=null,feedbackKind='wait';
const W=20,H=12,wall=new Set(),canvas=$('game'),ctx=canvas.getContext('2d');
const terminal={x:6,y:3},note={x:3,y:3},door={x:18,y:5};
function buildMap(){wall.clear();for(let y=0;y<H;y++)for(let x=0;x<W;x++){if(x===0||y===0||x===W-1||y===H-1)wall.add(`${x},${y}`)}for(let y=3;y<9;y++)if(y!==6)wall.add(`10,${y}`);for(let x=3;x<7;x++)wall.add(`${x},6`);for(let x=13;x<17;x++)wall.add(`${x},8`);for(let y=2;y<5;y++)wall.add(`15,${y}`);wall.add('6,3');wall.add('3,3')}
function nearby(o){return Math.abs(player.x-o.x)+Math.abs(player.y-o.y)<=1}
function translateStatic(){document.documentElement.lang=language;document.title=u.title+' · Python';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=u[el.dataset.i18n]);document.querySelectorAll('.close').forEach(el=>el.setAttribute('aria-label',u.close));canvas.setAttribute('aria-label',u.canvas);$('answer').placeholder=u.code;$('answer').setAttribute('aria-label',u.answer);document.querySelectorAll('[data-dir]').forEach((b,i)=>b.setAttribute('aria-label',u.directions[i]));document.querySelectorAll('[data-language]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.language===language));b.classList.toggle('selected',b.dataset.language===language)})}
function setLanguage(code){if(!UI[code])throw Error('Unsupported language');language=code;u=UI[code];chapters=LOCALES[code];try{localStorage.setItem('null-escape-language',code)}catch{}translateStatic();renderUI();if($('terminal').open)renderTerminal();if($('info').open)renderInfo()}
function renderUI(){const c=chapters[level];$('chapter').textContent=`${u.chapter} 0${level+1} / 05`;$('roomTitle').textContent=c.title;$('sector').textContent=`A–0${level+1}`;$('location').textContent=c.zone;$('goal').textContent=c.goal;$('objective').textContent=c.objective;$('skill').textContent=c.skill;$('missionNumber').textContent=`0${level+1}`;$('story').textContent=finished?(ending?u.freeLast:u.saveLast):solved[level]?u.solved:c.story;$('check').textContent=solved[level]?'✓':'○';$('task').textContent=finished?u.complete:solved[level]?u.through:u.activate;$('levels').innerHTML=chapters.map((c,i)=>`<li class="${i===level?'active':solved[i]?'done':''}"><span>${solved[i]?'✓':i+1}</span>${c.title}</li>`).join('');$('notes').textContent=`${collected.filter(Boolean).length} / 5 ↗`;updatePrompt()}
function updatePrompt(){let label=u.approach,enabled=false;if(nearby(terminal)){label=solved[level]?u.restored:u.openTerminal;enabled=true}else if(nearby(note)){label=collected[level]?u.read:u.collect;enabled=true}else if(nearby(door)){label=solved[level]?u.pass:u.locked;enabled=true}$('interact').disabled=!enabled||finished;$('interact').lastElementChild.textContent=label}
function showInfo(kind){infoKind=kind;renderInfo();if(!$('info').open)$('info').showModal()}
function renderInfo(){let html='';const c=chapters[level];if(infoKind==='note')html=`<div class="eyebrow">${u.record} 0${level+1}</div><h2>${u.identity}</h2><p>${c.note}</p>`;
if(infoKind==='denied')html=`<h2>${u.denied}</h2><p>${u.deniedBody}</p>`;
if(infoKind==='help')html=`<div class="eyebrow">${u.helpFrom}</div><h2>${u.helpTitle}</h2>${u.helpBody.map(p=>`<p>${p}</p>`).join('')}`;
if(infoKind==='choice')html=`<div class="eyebrow">${u.choice}</div><h2>${u.choiceTitle}</h2><p>${u.choiceBody}</p><div class="actions"><button class="quiet" id="saveMira">${u.save}</button><button class="primary" id="freeAll">${u.free}</button></div>`;
if(infoKind==='ending')html=`<div class="eyebrow">${u.done} / ${ending?u.dawn:u.endingSignal}</div><h2>${ending?u.freeTitle:u.saveTitle}</h2><p>${ending?u.freeBody:u.saveBody}</p><p>${u.learned} ${u.found}: ${collected.filter(Boolean).length}/5.</p><div class="actions"><button id="review" class="quiet">${u.review}</button><button id="restart" class="primary">${u.restart}</button></div>`;
if(infoKind==='journal')html=`<div class="eyebrow">${u.journal}</div><h2>${u.memory}</h2>`+chapters.map((c,i)=>`<div class="info-note"><strong>0${i+1} · ${c.skill}</strong><p>${solved[i]?c.concept:u.unlearned}</p><p>${collected[i]?c.note:u.missing}</p></div>`).join('')+(finished?`<button class="primary" id="again">${u.restart}</button>`:'');
$('infoContent').innerHTML=html;
if(infoKind==='choice'){$('saveMira').onclick=()=>finish(false);$('freeAll').onclick=()=>finish(true)}if(infoKind==='ending'){$('restart').onclick=restart;$('review').onclick=journal}if(infoKind==='journal'&&finished)$('again').onclick=restart;
}
function interact(){if(finished||$('terminal').open||$('info').open)return;if(nearby(terminal))openTerminal();else if(nearby(note)){collected[level]=true;renderUI();showInfo('note')}else if(nearby(door)){if(!solved[level])showInfo('denied');else if(level<4){level++;player={x:2,y:5};renderUI()}else showInfo('choice')}}
function renderTerminal(){const c=chapters[level];$('terminalId').textContent=`0${level+1}`;$('lessonTitle').textContent=c.skill;$('lesson').textContent=c.lesson;$('before').textContent=c.before;$('prefix').textContent=c.prefix;$('suffix').textContent=c.suffix;$('after').textContent=c.after;renderFeedback()}
function renderFeedback(){$('feedback').textContent=feedbackKind==='success'?'✓ '+chapters[level].success:feedbackKind==='hint'?chapters[level].hint:u[feedbackKind];$('feedback').style.borderColor=feedbackKind==='success'?'#c5f579':['wrong','wrongString','empty'].includes(feedbackKind)?'#d6a86b':'#718267'}
function openTerminal(){feedbackKind=solved[level]?'success':'wait';$('answer').value=solved[level]?chapters[level].answers[0]:'';renderTerminal();$('terminal').showModal();setTimeout(()=>$('answer').focus(),40)}
function check(){const raw=$('answer').value.trim();const valid=level===0?/^100$/.test(raw):level===1?/^("MIRA"|'MIRA')$/.test(raw):level===2?/^(access\s*==\s*3|3\s*==\s*access)$/.test(raw):level===3?/^3$/.test(raw):/^escape\s*\(\s*\)$/.test(raw);if(valid){solved[level]=true;feedbackKind='success';renderUI()}else feedbackKind=!raw?'empty':level===1?'wrongString':'wrong';renderFeedback();return valid}
function finish(all){finished=true;ending=all;showInfo('ending');renderUI()}
function restart(){level=0;solved.fill(false);collected.fill(false);player={x:3,y:8};finished=false;ending=null;steps=0;$('info').close();renderUI();canvas.focus()}
function journal(){showInfo('journal')}
function move(dx,dy){if(finished||$('terminal').open||$('info').open)return;const x=player.x+dx,y=player.y+dy;if(!wall.has(`${x},${y}`)&&x>=1&&x<W-1&&y>=1&&y<H-1){player={x,y};steps++;updatePrompt()}}
const dirs={w:[0,-1],ц:[0,-1],ArrowUp:[0,-1],s:[0,1],ы:[0,1],ArrowDown:[0,1],a:[-1,0],ф:[-1,0],ArrowLeft:[-1,0],d:[1,0],в:[1,0],ArrowRight:[1,0]};let lastMove=0;
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)){if(e.key==='Enter'){e.preventDefault();check()}return}if($('terminal').open||$('info').open)return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(dirs[k]){e.preventDefault();if(!e.repeat||performance.now()-lastMove>85){move(...dirs[k]);lastMove=performance.now()}}if(k==='e'||k==='у'){e.preventDefault();interact()}});
$('interact').onclick=interact;$('run').onclick=check;$('hint').onclick=()=>{feedbackKind='hint';renderFeedback()};$('journal').onclick=journal;$('help').onclick=()=>showInfo('help');
document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>setLanguage(b.dataset.language));
document.querySelectorAll('[data-dir]').forEach(b=>{const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[b.dataset.dir];let timer;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);move(...d);timer=setInterval(()=>move(...d),130)};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>clearInterval(timer)});
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h)}
function draw(t){const S=48;ctx.clearRect(0,0,960,576);rect(0,0,960,576,'#101a18');for(let y=0;y<H;y++)for(let x=0;x<W;x++){let px=x*S,py=y*S;if(wall.has(`${x},${y}`)){rect(px,py,S,S,'#263631');rect(px+2,py+2,S-4,S-9,'#30413a');rect(px+4,py+5,S-8,2,'#405148');rect(px+3,py+S-8,S-6,5,'#14231e')}else{rect(px+1,py+1,S-2,S-2,(x+y)%2?'#182620':'#1b2923');rect(px+5,py+5,2,2,'#2b3a2d')}}
// Functional route markings, terminals, exit and player on the tile map.
ctx.globalAlpha=.2;for(let x=2;x<18;x++)rect(x*S+21,5*S+22,12,3,'#9cbd6c');ctx.globalAlpha=1;
for(const [x,y] of [[1,1],[8,1],[17,1],[1,10],[8,10],[17,10]]){ctx.shadowBlur=20;ctx.shadowColor='#add993';rect(x*S+8,y*S+10,28,4,'#94ad79');ctx.shadowBlur=0}
const tx=terminal.x*S,ty=terminal.y*S;rect(tx-3,ty-6,54,58,'#111d17');rect(tx+3,ty,42,33,'#526344');ctx.shadowBlur=18;ctx.shadowColor='#a5ed67';rect(tx+8,ty+5,32,22,solved[level]?'#c9f087':'#82cc66');ctx.shadowBlur=0;ctx.fillStyle='#234124';ctx.font='bold 18px monospace';ctx.fillText('>_',tx+10,ty+22);rect(tx+4,ty+37,40,7,'#6c8060');
ctx.fillStyle='#a8c794';ctx.font='11px monospace';ctx.textAlign='center';ctx.fillText(solved[level]?u.online:u.terminal,tx+24,ty-18);
const nx=note.x*S+24,ny=note.y*S+24;ctx.shadowBlur=collected[level]?0:18+5*Math.sin(t/400);ctx.shadowColor='#e9b76a';rect(nx-11,ny-13,22,26,collected[level]?'#71664c':'#dbb374');ctx.shadowBlur=0;rect(nx-6,ny-7,12,2,'#70532e');rect(nx-6,ny-1,12,2,'#70532e');rect(nx-6,ny+5,8,2,'#70532e');
const dx=door.x*S,dy=door.y*S;rect(dx-5,dy-25,53,100,'#0c1511');rect(dx,dy-20,42,90,solved[level]?'#243e24':'#343b2c');for(let i=0;i<5;i++)rect(dx+4,dy-15+i*17,34,2,'#48583b');ctx.shadowBlur=20;ctx.shadowColor=solved[level]?'#bef579':'#d8ac62';rect(dx-3,dy-20,4,90,solved[level]?'#bef579':'#d8ac62');ctx.shadowBlur=0;ctx.fillStyle=solved[level]?'#c5f579':'#bbaa7a';ctx.fillText(u.exit,dx+18,dy-33);
const px=player.x*S+24,py=player.y*S+25;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(px,py+18,18,7,0,0,Math.PI*2);ctx.fill();ctx.shadowBlur=22;ctx.shadowColor='#bbf282';rect(px-12,py-5,24,23,'#adce85');ctx.shadowBlur=0;rect(px-9,py-22,18,18,'#d4dfb4');rect(px-8,py-17,16,7,'#253b31');rect(px+1,py-16,6,3,'#ade8a5');rect(px-11,py+16,8,10,'#536947');rect(px+3,py+16,8,10,'#536947');rect(px-17,py-2,5,16,'#758f5b');rect(px+12,py-2,5,16,'#758f5b');ctx.fillStyle='#c5f579';ctx.beginPath();ctx.moveTo(px-4,py-36);ctx.lineTo(px+4,py-36);ctx.lineTo(px,py-31);ctx.fill();ctx.textAlign='left';requestAnimationFrame(draw)}

buildMap();translateStatic();renderUI();requestAnimationFrame(draw);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_escape_progress',description:'Прочитать текущую главу, изученные навыки и число найденных записей.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('Ожидается пустой объект');return{chapter:level+1,title:chapters[level].title,language,skills:chapters.filter((_,i)=>solved[i]).map(c=>c.skill),notes:collected.filter(Boolean).length,finished}}})).catch(()=>{})}catch{}}
